// LIST MOVIES
export const GET_MOVIES_LIST_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_MOVIES_LIST_FAIL = "GET_MOVIES_LIST_FAIL";
export const GET_MOVIE_SUCCES = "GET_MOVIE_SUCCES";
export const GET_MOVIE_FAIL = "GET_MOVIE_FAIL";

//